### ISSUE TITLE
Could not find a package configuration file provided by "CoppeliaSim" (requested version 4.1.0.0) with any of the following names

### ISSUE THREAD

**Issue by zhangm365** [CoppeliaRobotics/v_repExtPluginSkeletonNG#1]
I am trying to compiling the libPlugin, but the error is as follow:
![image](https://user-images.githubusercontent.com/22396672/151331202-e8bbafa9-a095-4308-8a6e-2314ea16ca0c.png)

Can you give me a hand?

**Comment by fferri** [comment]
You need to set `COPPELIASIM_ROOT_DIR` environment variable to point to the CoppeliaSim directory that contains the programming folder.

**Comment by zhangm365** [comment]
![image](https://user-images.githubusercontent.com/22396672/151356376-bb94d484-b986-4336-9561-c7bd72cf11fe.png)


As above set, the error is same.

**Comment by fferri** [comment]
If you read my comment more carefully you'll find out it's another variable I told you to set.
Note the fact it's an **environment** variable, not a **CMake** variable.
And the correct value would be `C:/Program Files/CoppeliaRobotics/CoppeliaSimEdu`.
Also, remember to clear the CMake cache between one run and another.

Probably the most convenient thing to do is set it globally as explained here:
https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

**Comment by zhangm365** [comment]
OK, Thanks a lot.

Now, the Boost is installed and set the environment variable, but the error is as follow:

![image](https://user-images.githubusercontent.com/22396672/151503938-d0c0f0c1-2bc6-4359-b922-eb4e8c2b7a73.png)

**Comment by fferri** [comment]
Boost missing?

**Comment by zhangm365** [comment]
The Boost is installed, but the error occurs.

**Comment by fferri** [comment]
Clearly Boost cannot be found. Depending on how you installed Boost you need to set some CMake variables.

Related: www.google.com/search?q=windows+could+not+find+boost

**Comment by zhangm365** [comment]
ok, I solved the error. Thanks a lot.

**Comment by zhangm365** [comment]
Besides, what is the difference between this repos and the [simExtPluginSkeleton](https://github.com/CoppeliaRobotics/simExtPluginSkeleton)?

**Comment by Coppelia** [comment]
simExtPluginSkeleton is a plugin skeleton that is using an older way to interface with CoppeliaSim. It is less flexible, but can be a bit easier to understand and use for plugins with little API functions

**Comment by zhangm365** [comment]
OK, Thanks a lot.

I am trying to use a customed inverse-kinematic algorithm instead of the built-in algorithm (**DLS**) to calculate the inverse kinematics problem. How can I do and what is the guiding route of this process?

**Comment by Coppelia** [comment]
Please ask in the CoppeliaSim forum

**Comment by zhangm365** [comment]
ok, Thanks a lot
